### ISSUE TITLE
wait for postgress better errors

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/kosko-charts#153]
Errors from wait-for-postgres are misleading, should be more explicit

**Comment by douglasduteil** [comment]
@revolunet is it fixed with https://github.com/SocialGouv/docker/commit/a10047647c77e9c2dae9c476fd4df620bf0e1410 ?

![image](https://user-images.githubusercontent.com/730511/96227975-35ace880-0f95-11eb-994b-671b556ba346.png)
\from https://gitlab.factory.social.gouv.fr/SocialGouv/docker/-/jobs/1021392

**Comment by revolunet** [comment]
yep thanks !
